# Generated by Django 3.1 on 2021-08-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myconcretecasting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsite',
            name='jobsite_description',
            field=models.TextField(blank=True),
        ),
    ]
