# Generated by Django 3.1 on 2021-08-15 15:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myconcretecasting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('isClassEI', models.BooleanField()),
                ('fcm2_fcm28_ratio', models.IntegerField(null=True)),
                ('type2_addition', models.BooleanField()),
                ('rc2_rc28_ratio', models.IntegerField(null=True)),
                ('cement_type', models.CharField(max_length=50)),
                ('curing_start', models.DateTimeField(default=None, null=True)),
                ('curing_end', models.DateTimeField(default=None, null=True)),
            ],
        ),
    ]
