# Generated by Django 3.1 on 2021-08-05 14:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myconcretecasting', '0002_auto_20210804_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casting',
            fields=[
                ('casting_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('casting_name', models.CharField(max_length=50)),
                ('casting_description', models.TextField(blank=True)),
                ('casting_isClassEI', models.BooleanField()),
                ('casting_fcm2_fcm28_ratio', models.IntegerField(null=True)),
                ('casting_type2_addition', models.BooleanField()),
                ('casting_rc2_rc28_ratio', models.IntegerField(null=True)),
                ('casting_cement_type', models.CharField(max_length=50)),
            ],
        ),
    ]
