# Generated by Django 3.1 on 2021-06-18 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concretetracker', '0002_auto_20210618_1513'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Casting',
        ),
    ]
