# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Npm Install
        working-directory: ./frontend
        run: npm ci

      - name: Npm test
        working-directory: ./frontend
        run: npm test --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Npm Build
        working-directory: ./frontend
        run: mkdir -p dist/frontend/ && npm run build --if-present
